main:
  steps:
    - run_training:
        call: http.post
        args:
          url: ${"https://europe-west3-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/" + sys.get_env("GOOGLE_CLOUD_PROJECT_ID") + "/jobs/training:run"}
          auth:
            type: OAuth2
        result: training_result
    - run_inference:
        call: http.post
        args:
          url: ${"https://europe-west3-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/" + sys.get_env("GOOGLE_CLOUD_PROJECT_ID") + "/jobs/inference:run"}
          auth:
            type: OAuth2
        result: inference_result
    - done:
        return: "Pipeline completed!"
